### ISSUE TITLE
Heating status doesn't trigger

### ISSUE THREAD

**Issue by Keverjeroen** [magtimmermans/com.cyclone-software.atagone#1]
Hi,

I'm still a daily user of this great app! It's one of the most stable Homey apps. 👍 

Now I want to make a flow that triggers om the change of the heating status  (heating is changed). I think this trigger will be triggered if the heater starts heating and stops heating (burner on/off). If that's right, it doesn't trigger over here..

Maybe you can check this if you have time for it.

p.s. one translate suggestion from English to Dutch:
"en": "Heating is changed",
"nl": "Verwarming status is veranderd"

Thanks!

**Comment by magtimmermans** [comment]
Hi,

I think I have used the wrong data. Basically you have 3 different statuses:

boilerHeating
Central Heating
Domestic Hot Water Heating

I am not sure what the top one will be, I guess if one of 2 is active the boilerHeating will be active. 

I will try this one. Is this oke you think?

**Comment by magtimmermans** [comment]
I have put a new version on live with the status boiler heating change. This will change when hot water is used or central heating. When I have more time I will add the rest.  Please be aware that the polling takes place every 5 minutes.

**Comment by Keverjeroen** [comment]
Wow, that's fast! Did u submitted it to the store? Then i'll update and test it as soon as it's there.

**Comment by magtimmermans** [comment]
Can you first test it? Or is this complex for you, than I will publish this to the store as it is now also not correct :)

**Comment by Keverjeroen** [comment]
Can't install via CLI get this error:

_✓ Validating app...
✘ Homey App did not validate against level `debug`:
[
    {
        "keyword": "enum",
        "dataPath": ".flow.conditions[0].args[0].type",
        "schemaPath": "#/properties/args/items/oneOf/0/properties/type/enum",
        "params": {
            "allowedValues": [
                "text",
                "autocomplete",
                "device",
                "date",
                "time",
                "color"
            ]
        },
        "message": "should be equal to one of the allowed values"
    },
    {
        "keyword": "type",
        "dataPath": ".flow.conditions[0].args[0].min",
        "schemaPath": "#/properties/args/items/oneOf/1/properties/min/type",
        "params": {
            "type": "number"
        },
        "message": "should be number"
    },
    {
        "keyword": "enum",
        "dataPath": ".flow.conditions[0].args[0].type",
        "schemaPath": "#/properties/args/items/oneOf/2/properties/type/enum",
        "params": {
            "allowedValues": [
                "dropdown"
            ]
        },
        "message": "should be equal to one of the allowed values"
    },
    {
        "keyword": "oneOf",
        "dataPath": ".flow.conditions[0].args[0]",
        "schemaPath": "#/properties/args/items/oneOf",
        "params": {
            "passingSchemas": null
        },
        "message": "should match exactly one schema in oneOf"
    }
]
Not installing, please fix the validation issues first_

**Comment by magtimmermans** [comment]
Mmh, This is wierd. I do not recognize this code. Also I have installed it the same way??

**Comment by Keverjeroen** [comment]
Whoops.. There was an old package of this app in the same folder on my laptop.. :)

Now the install process starts, but I see that I have to be in the same network as Homey (it wants to connect to the local IP of Homey), so I have to try it again from home later.

**Comment by magtimmermans** [comment]
hi, it is also on the app store as beta.

**Comment by Keverjeroen** [comment]
Thanks. Can't find the beta in the app store. Guess it's waiting for aprovement?

**Comment by magtimmermans** [comment]
Now it is :) Forgot to commit
