### ISSUE TITLE
Can 't save settings ATAG One App

### ISSUE THREAD

**Issue by Olliebertolli** [magtimmermans/com.cyclone-software.atagone#3]
I cannot save settings with homey V2.0 when I am using an if card: if temperature is lower than 12 degrees..... 
After filling in temperature I need to select ATAG One as device to read temperature from. I can't save these settings.

**Comment by magtimmermans** [comment]
Today there will be an update to the beta branch

**Comment by magtimmermans** [comment]
Beta version published
