### ISSUE TITLE
Cannot install on Homey 2.0.0 

### ISSUE THREAD

**Issue by johij** [magtimmermans/com.cyclone-software.atagone#4]
i have seen the beta branch but i cannot find a way to install this on my homey

**Comment by magtimmermans** [comment]
you can do this using athom-cli (developers tools) or you need to wait until the app is approved for beta in the store.

**Comment by johij** [comment]
thanks, i'm new to homey but got it installed but everytime it has a timeout if i try to add the atag one.

**Comment by magtimmermans** [comment]
Did you accept on de atag one device? Is this your first time you connect? Or did you had a previous version installed?

**Comment by johij** [comment]
i was waiting for the question on the atag one but nothing is popping up. But it cannot find the atag one. But the atag app connect with it right away. it is the first time i'm trying to connect

**Comment by magtimmermans** [comment]
I hope I have fixed it. Please try again

**Comment by johij** [comment]
works like a charm!!! thanks for the quick fix

**Comment by magtimmermans** [comment]
Great!
