### ISSUE TITLE
New Atag one not able to add

### ISSUE THREAD

**Issue by theguide1234** [magtimmermans/com.cyclone-software.atagone#6]
Hi, I've just got myself a Atag One. The installer informed me that this was a new version (Fw 122.35.58D / Sw 1.7.7044.21260) because the link between Atag iOS App was much quicker.

Now I can't get the Atag One added to my Homey. Did some investigations myself and I've noticed via Whireshark that my One isn't broadcasting all the time, only for a short moment when I try to re-link via the iOS app it sends a couple of broadcasts but that's all.

Please support here, if you need debugging data contact me.

**Comment by magtimmermans** [comment]
Hi,

Did you manage to connect?

**Comment by tomm501** [comment]
Hi,

No I haven't so far, I tried but it doesn't show up in the connection
screen in the app.




Op vr 25 okt. 2019 08:09 schreef magtimmermans <notifications@github.com>:

**Comment by theguide1234** [comment]
No, still no connection between Atag and Homey.

**Comment by magtimmermans** [comment]
I try to reproduce it. I know that the amount of time is short. I use my phone and stay with the ATAG One to connect it.  Do you have some debug information..

**Comment by theguide1234** [comment]
Sorry for the delay @magtimmermans, just tried to add my Atag One Again:

* Started Wireshark on laptop
* Add via Atag App: result = `<font color="red"><b>Device not found</b></font>`
* Log file Atag App: 
`onPair 
onPair
2019-11-01 13:51:35 [log] [AtagOneApp] logfile deleted`
* In Wireshark no broadcast from Atag one visible
* Send Diag report `b6c436b2-9c14-4ce1-b138-f419761ec2c9` via Homey app.

If you need more just let me know.

_Note: updated Homey to 3.0 this morning_

**Comment by magtimmermans** [comment]
I am curious if the ATAG device is responding or send information. Could you monitor the traffic from this device?

**Comment by conceptblenders** [comment]
I'm also having the <font color="red"><b>Device not found</b></font> message. Do I need to put the Atag One in a certain mode to be detected?
Or is it due to the new Atag One Zone?

**Comment by conceptblenders** [comment]
Diag report: c09fa9ab-191a-4bce-8ac9-2d02bc622306

**Comment by magtimmermans** [comment]
Do you have a atag one or zone? Because zone is not supported.

**Comment by conceptblenders** [comment]
Ah bummer.. hoped it was..
Did you do some research to zone?
Does it have a different approach? 
Do you know if your code could provide a base for a zone version?
I’m a programmer too.

Regards,
Maarten 

Verstuurd vanaf mijn iPhone

**Comment by magtimmermans** [comment]
Hi, I have never seen the zone my self and looked to the protocol so I am not sure if it is the same. I imagine it is.

**Comment by conceptblenders** [comment]
At the moment it  seems that your broadcast looks for a specific thing. Have to review your code, can you talk me trough the detection process?
Maybe the Zone is called different.

Verstuurd vanaf mijn iPhone

**Comment by magtimmermans** [comment]
Hi, it makes a datagram socket to listen to UDP messages on port 11000. The one reacts then with a message with 37 chars. The text in this message contains the word ONE which I am detecting. So you could log the full text before I check on the ONE message and maybe you see ZONE or so.

**Comment by conceptblenders** [comment]
Thanks. That’s what I was thinking, it must be the word ONE that is different here. 
Christmas days provide a lot of time for me to find this out. I will let you know if I succeed.

Just one last question, is the One also a HomeKit enabled device?

**Comment by conceptblenders** [comment]
I found out that the ONE is wifi-connected, just as the ZONE, but the ZONE uses HomeKit and with that it is totally different.
I’m gonna look for another thermostat.

**Comment by magtimmermans** [comment]
Aha, that's indeed totally different.  At least we know now.  Goodluck finding something else.
