### ISSUE TITLE
Temperature misconfigured

### ISSUE THREAD

**Issue by johnotte** [magtimmermans/com.cyclone-software.atagone#9]
Outside temperature is currently presented as -100 while actual outside temperature is -4,4 on the ATAG one.

**Comment by magtimmermans** [comment]
Unfortunatly I am not owning a ATAG One anymore. Are you able to run the app from the command line and see the debugging log? This might help to identify the issue.

**Comment by johnotte** [comment]
Zodra ik dat heb uitgevogeld hoe zal ik dat doen.GrtJohnVerzonden vanaf mijn Galaxy
-------- Oorspronkelijk bericht --------Van: magtimmermans <notifications@github.com> Datum: 08-02-2021  14:59  (GMT+01:00) Aan: "magtimmermans/com.cyclone-software.atagone" <com.cyclone-software.atagone@noreply.github.com> Cc: johnotte <john.otte@upcmail.nl>, Author <author@noreply.github.com> Onderwerp: Re: [magtimmermans/com.cyclone-software.atagone] Temperature misconfigured (#9) 
Unfortunatly I am not owning a ATAG One anymore. Are you able to run the app from the command line and see the debugging log? This might help to identify the issue.
